spring.application.name=API-GATEWAY
server.port=9191

#configure eureka url for deparment and employee
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*

## automatically configure routes for employee and deparment service by setting
## discovery locator to true which default is false
#spring.cloud.gateway.discovery.locator.enabled=true

##convert all uppercase letters to lowercase.thus converts services id in uppercase to lowercase
## e.g EMPLOYEE-SERVICE to employee-service 
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

## enable logging for the api gateway
#logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=DEBUG


##manully creates or configure Routes for employee service 
spring.cloud.gateway.routes[0].id=EMPLOYEE-SERVICE

#routes with load balaning
spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE

#configure rest api path(predicate)
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**

##manully creates or configure Routes for department service
spring.cloud.gateway.routes[1].id=DEPARTMENT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/departments/**

##manully creates or configure Routes for organization service
spring.cloud.gateway.routes[2].id=ORGANIZATION-SERVICE
spring.cloud.gateway.routes[2].uri=lb://ORGANIZATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/organizations/**

management.tracing.enabled=true
# configure sampling and loging pattern for all incoming request
management.tracing.sampling.probability=1.0

#zipkin base url
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

#Actuator endpoints for Circuit Breaker
#management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.exclude=health
management.endpoint.health.show-details=always

#cross-origin resource sharing(cors) configuration 
# * means any application can access the rest api
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
# http methods allowed
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE




